import Head from 'next/head';
import { getArticlesData } from 'lib/articles';
import { InferGetServerSidePropsType } from 'next';

interface ArticleProps {
  id: string;
  date?: string;
  title?: string;
}

export async function getStaticProps() {
  const allArticlesData: ArticleProps[] = getArticlesData();
  return {
    props: {
      allArticlesData,
    },
  };
}

export default function Home({
  allArticlesData,
}: InferGetServerSidePropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Marina Monster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-indigo-600">Work in progress</p>
        <ul>
          {allArticlesData.map(({ id, date, title }) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
