import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Marina Monster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-indigo-600">Work in progress</p>
      </main>
    </>
  );
}
